import type { Currency, CurrencyConfig } from './types'

export const CURRENCY_CONFIG: Record<string, CurrencyConfig> = {
  USD: { name: 'US Dollar',            symbol: '$',    flag: '🇺🇸', country: 'United States' },
  EUR: { name: 'Euro',                  symbol: '€',    flag: '🇪🇺', country: 'European Union' },
  GBP: { name: 'British Pound',         symbol: '£',    flag: '🇬🇧', country: 'United Kingdom' },
  FKP: { name: 'Falkland Islands Pound', symbol: '£',   flag: '🇫🇰', country: 'Falkland Islands' },
  GGP: { name: 'Guernsey Pound',         symbol: '£',   flag: '🇬🇬', country: 'Guernsey' },
  GIP: { name: 'Gibraltar Pound',         symbol: '£',   flag: '🇬🇮', country: 'Gibraltar' },
  JEP: { name: 'Jersey Pound',            symbol: '£',   flag: '🇯🇪', country: 'Jersey' },
  SHP: { name: 'Saint Helena Pound',      symbol: '£',   flag: '🇸🇭', country: 'Saint Helena' },
  JPY: { name: 'Japanese Yen',          symbol: '¥',    flag: '🇯🇵', country: 'Japan' },
  CHF: { name: 'Swiss Franc',           symbol: 'Fr',   flag: '🇨🇭', country: 'Switzerland' },
  CAD: { name: 'Canadian Dollar',       symbol: '$',    flag: '🇨🇦', country: 'Canada' },
  AUD: { name: 'Australian Dollar',     symbol: '$',    flag: '🇦🇺', country: 'Australia' },
  CNY: { name: 'Chinese Yuan',          symbol: '¥',    flag: '🇨🇳', country: 'China' },
  INR: { name: 'Indian Rupee',          symbol: '₹',    flag: '🇮🇳', country: 'India' },
  KRW: { name: 'South Korean Won',      symbol: '₩',    flag: '🇰🇷', country: 'South Korea' },
  MXN: { name: 'Mexican Peso',          symbol: '$',    flag: '🇲🇽', country: 'Mexico' },
  BRL: { name: 'Brazilian Real',        symbol: 'R$',   flag: '🇧🇷', country: 'Brazil' },
  SEK: { name: 'Swedish Krona',         symbol: 'kr',   flag: '🇸🇪', country: 'Sweden' },
  NOK: { name: 'Norwegian Krone',       symbol: 'kr',   flag: '🇳🇴', country: 'Norway' },
  DKK: { name: 'Danish Krone',          symbol: 'kr',   flag: '🇩🇰', country: 'Denmark' },
  FOK: { name: 'Faroese Króna',         symbol: 'kr',   flag: '🇫🇴', country: 'Faroe Islands' },
  NZD: { name: 'New Zealand Dollar',    symbol: '$',    flag: '🇳🇿', country: 'New Zealand' },
  SGD: { name: 'Singapore Dollar',      symbol: '$',    flag: '🇸🇬', country: 'Singapore' },
  HKD: { name: 'Hong Kong Dollar',      symbol: '$',    flag: '🇭🇰', country: 'Hong Kong' },
  THB: { name: 'Thai Baht',             symbol: '฿',    flag: '🇹🇭', country: 'Thailand' },
  TRY: { name: 'Turkish Lira',          symbol: '₺',    flag: '🇹🇷', country: 'Turkey' },
  ZAR: { name: 'South African Rand',    symbol: 'R',    flag: '🇿🇦', country: 'South Africa' },
  BWP: { name: 'Botswana Pula',         symbol: 'P',    flag: '🇧🇼', country: 'Botswana' },
  AED: { name: 'UAE Dirham',            symbol: 'د.إ',  flag: '🇦🇪', country: 'United Arab Emirates' },
  PLN: { name: 'Polish Złoty',          symbol: 'zł',   flag: '🇵🇱', country: 'Poland' },
  PHP: { name: 'Philippine Peso',       symbol: '₱',    flag: '🇵🇭', country: 'Philippines' },
  // New currencies from ExchangeRate-API
  CZK: { name: 'Czech Koruna',          symbol: 'Kč',   flag: '🇨🇿', country: 'Czech Republic' },
  HUF: { name: 'Hungarian Forint',      symbol: 'Ft',   flag: '🇭🇺', country: 'Hungary' },
  IDR: { name: 'Indonesian Rupiah',     symbol: 'Rp',   flag: '🇮🇩', country: 'Indonesia' },
  ILS: { name: 'Israeli Shekel',        symbol: '₪',    flag: '🇮🇱', country: 'Israel' },
  MYR: { name: 'Malaysian Ringgit',     symbol: 'RM',   flag: '🇲🇾', country: 'Malaysia' },
  RON: { name: 'Romanian Leu',          symbol: 'lei',  flag: '🇷🇴', country: 'Romania' },
  ISK: { name: 'Icelandic Króna',       symbol: 'kr',   flag: '🇮🇸', country: 'Iceland' },
  CLP: { name: 'Chilean Peso',          symbol: '$',    flag: '🇨🇱', country: 'Chile' },
  COP: { name: 'Colombian Peso',        symbol: '$',    flag: '🇨🇴', country: 'Colombia' },
  ARS: { name: 'Argentine Peso',        symbol: '$',    flag: '🇦🇷', country: 'Argentina' },
  PEN: { name: 'Peruvian Sol',          symbol: 'S/',   flag: '🇵🇪', country: 'Peru' },
  EGP: { name: 'Egyptian Pound',        symbol: '£',    flag: '🇪🇬', country: 'Egypt' },
  NGN: { name: 'Nigerian Naira',        symbol: '₦',    flag: '🇳🇬', country: 'Nigeria' },
  KWD: { name: 'Kuwaiti Dinar',         symbol: 'KD',   flag: '🇰🇼', country: 'Kuwait' },
  SAR: { name: 'Saudi Riyal',           symbol: '﷼',    flag: '🇸🇦', country: 'Saudi Arabia' },
  QAR: { name: 'Qatari Riyal',          symbol: '﷼',    flag: '🇶🇦', country: 'Qatar' },
  UAH: { name: 'Ukrainian Hryvnia',     symbol: '₴',    flag: '🇺🇦', country: 'Ukraine' },
  VND: { name: 'Vietnamese Dong',       symbol: '₫',    flag: '🇻🇳', country: 'Vietnam' },
  TWD: { name: 'Taiwan Dollar',         symbol: 'NT$',  flag: '🇹🇼', country: 'Taiwan' },
  PKR: { name: 'Pakistani Rupee',       symbol: '₨',    flag: '🇵🇰', country: 'Pakistan' },
  BDT: { name: 'Bangladeshi Taka',      symbol: '৳',    flag: '🇧🇩', country: 'Bangladesh' },
  BGN: { name: 'Bulgarian Lev',         symbol: 'лв',   flag: '🇧🇬', country: 'Bulgaria' },
  HRK: { name: 'Croatian Kuna',         symbol: 'kn',   flag: '🇭🇷', country: 'Croatia' },
  RSD: { name: 'Serbian Dinar',         symbol: 'din',  flag: '🇷🇸', country: 'Serbia' },
  RUB: { name: 'Russian Ruble',          symbol: '₽',    flag: '🇷🇺', country: 'Russia' },
  GEL: { name: 'Georgian Lari',         symbol: '₾',    flag: '🇬🇪', country: 'Georgia' },
  AMD: { name: 'Armenian Dram',         symbol: '֏',    flag: '🇦🇲', country: 'Armenia' },
  KZT: { name: 'Kazakhstani Tenge',     symbol: '₸',    flag: '🇰🇿', country: 'Kazakhstan' },
  UZS: { name: 'Uzbekistani Som',       symbol: "so'm", flag: '🇺🇿', country: 'Uzbekistan' },
  AZN: { name: 'Azerbaijani Manat',     symbol: '₼',    flag: '🇦🇿', country: 'Azerbaijan' },
  BYN: { name: 'Belarusian Ruble',      symbol: 'Br',   flag: '🇧🇾', country: 'Belarus' },
  MDL: { name: 'Moldovan Leu',          symbol: 'L',    flag: '🇲🇩', country: 'Moldova' },
  MAD: { name: 'Moroccan Dirham',       symbol: 'MAD',  flag: '🇲🇦', country: 'Morocco' },
  TND: { name: 'Tunisian Dinar',        symbol: 'DT',   flag: '🇹🇳', country: 'Tunisia' },

  // Africa
  DZD: { name: 'Algerian Dinar',              symbol: 'DA',   flag: '🇩🇿', country: 'Algeria' },
  ETB: { name: 'Ethiopian Birr',               symbol: 'Br',   flag: '🇪🇹', country: 'Ethiopia' },
  GHS: { name: 'Ghanaian Cedi',                symbol: '₵',    flag: '🇬🇭', country: 'Ghana' },
  KES: { name: 'Kenyan Shilling',              symbol: 'KSh',  flag: '🇰🇪', country: 'Kenya' },
  LYD: { name: 'Libyan Dinar',                 symbol: 'LD',   flag: '🇱🇾', country: 'Libya' },
  MUR: { name: 'Mauritian Rupee',              symbol: '₨',    flag: '🇲🇺', country: 'Mauritius' },
  MZN: { name: 'Mozambican Metical',           symbol: 'MT',   flag: '🇲🇿', country: 'Mozambique' },
  RWF: { name: 'Rwandan Franc',                symbol: 'RF',   flag: '🇷🇼', country: 'Rwanda' },
  BIF: { name: 'Burundian Franc',              symbol: 'Fr',   flag: '🇧🇮', country: 'Burundi' },
  SDG: { name: 'Sudanese Pound',               symbol: '£',    flag: '🇸🇩', country: 'Sudan' },
  SSP: { name: 'South Sudanese Pound',         symbol: '£',    flag: '🇸🇸', country: 'South Sudan' },
  SOS: { name: 'Somali Shilling',              symbol: 'Sh',   flag: '🇸🇴', country: 'Somalia' },
  SZL: { name: 'Swazi Lilangeni',              symbol: 'L',    flag: '🇸🇿', country: 'Eswatini' },
  TZS: { name: 'Tanzanian Shilling',           symbol: 'TSh',  flag: '🇹🇿', country: 'Tanzania' },
  UGX: { name: 'Ugandan Shilling',             symbol: 'USh',  flag: '🇺🇬', country: 'Uganda' },
  XAF: { name: 'CFA Franc BEAC',               symbol: 'Fr',   flag: '🇨🇲', country: 'Central Africa' },
  XOF: { name: 'CFA Franc BCEAO',              symbol: 'Fr',   flag: '🇸🇳', country: 'West Africa' },
  ZMW: { name: 'Zambian Kwacha',               symbol: 'ZK',   flag: '🇿🇲', country: 'Zambia' },
  ZWL: { name: 'Zimbabwean Dollar',            symbol: '$',    flag: '🇿🇼', country: 'Zimbabwe' },
  GNF: { name: 'Guinean Franc',                symbol: 'Fr',   flag: '🇬🇳', country: 'Guinea' },
  MWK: { name: 'Malawian Kwacha',              symbol: 'MK',   flag: '🇲🇼', country: 'Malawi' },
  NAD: { name: 'Namibian Dollar',              symbol: '$',    flag: '🇳🇦', country: 'Namibia' },
  SCR: { name: 'Seychellois Rupee',            symbol: '₨',    flag: '🇸🇨', country: 'Seychelles' },
  KMF: { name: 'Comorian Franc',              symbol: 'Fr',   flag: '🇰🇲', country: 'Comoros' },
  CVE: { name: 'Cape Verdean Escudo',          symbol: '$',    flag: '🇨🇻', country: 'Cape Verde' },
  DJF: { name: 'Djiboutian Franc',             symbol: 'Fr',   flag: '🇩🇯', country: 'Djibouti' },
  ERN: { name: 'Eritrean Nakfa',               symbol: 'Nfk',  flag: '🇪🇷', country: 'Eritrea' },
  GMD: { name: 'Gambian Dalasi',               symbol: 'D',    flag: '🇬🇲', country: 'Gambia' },
  SLE: { name: 'Sierra Leonean Leone',         symbol: 'Le',   flag: '🇸🇱', country: 'Sierra Leone' },
  LRD: { name: 'Liberian Dollar',              symbol: '$',    flag: '🇱🇷', country: 'Liberia' },
  LSL: { name: 'Lesotho Loti',                 symbol: 'L',    flag: '🇱🇸', country: 'Lesotho' },
  MGA: { name: 'Malagasy Ariary',              symbol: 'Ar',   flag: '🇲🇬', country: 'Madagascar' },
  MRU: { name: 'Mauritanian Ouguiya',          symbol: 'UM',   flag: '🇲🇷', country: 'Mauritania' },
  STN: { name: 'São Tomé & Príncipe Dobra',    symbol: 'Db',   flag: '🇸🇹', country: 'São Tomé & Príncipe' },
  AOA: { name: 'Angolan Kwanza',               symbol: 'Kz',   flag: '🇦🇴', country: 'Angola' },
  CDF: { name: 'Congolese Franc',              symbol: 'Fr',   flag: '🇨🇩', country: 'DR Congo' },

  // Middle East & Asia
  AFN: { name: 'Afghan Afghani',               symbol: '؋',    flag: '🇦🇫', country: 'Afghanistan' },
  BHD: { name: 'Bahraini Dinar',               symbol: 'BD',   flag: '🇧🇭', country: 'Bahrain' },
  IQD: { name: 'Iraqi Dinar',                  symbol: 'ID',   flag: '🇮🇶', country: 'Iraq' },
  IRR: { name: 'Iranian Rial',                 symbol: '﷼',    flag: '🇮🇷', country: 'Iran' },
  JOD: { name: 'Jordanian Dinar',              symbol: 'JD',   flag: '🇯🇴', country: 'Jordan' },
  KHR: { name: 'Cambodian Riel',               symbol: '៛',    flag: '🇰🇭', country: 'Cambodia' },
  LAK: { name: 'Lao Kip',                      symbol: '₭',    flag: '🇱🇦', country: 'Laos' },
  LBP: { name: 'Lebanese Pound',               symbol: 'L£',   flag: '🇱🇧', country: 'Lebanon' },
  LKR: { name: 'Sri Lankan Rupee',             symbol: '₨',    flag: '🇱🇰', country: 'Sri Lanka' },
  MMK: { name: 'Myanmar Kyat',                 symbol: 'K',    flag: '🇲🇲', country: 'Myanmar' },
  MNT: { name: 'Mongolian Tögrög',             symbol: '₮',    flag: '🇲🇳', country: 'Mongolia' },
  MVR: { name: 'Maldivian Rufiyaa',            symbol: 'Rf',   flag: '🇲🇻', country: 'Maldives' },
  NPR: { name: 'Nepalese Rupee',               symbol: '₨',    flag: '🇳🇵', country: 'Nepal' },
  OMR: { name: 'Omani Rial',                   symbol: 'ر.ع.', flag: '🇴🇲', country: 'Oman' },
  SYP: { name: 'Syrian Pound',                 symbol: '£',    flag: '🇸🇾', country: 'Syria' },
  TMT: { name: 'Turkmenistani Manat',          symbol: 'T',    flag: '🇹🇲', country: 'Turkmenistan' },
  YER: { name: 'Yemeni Rial',                  symbol: '﷼',    flag: '🇾🇪', country: 'Yemen' },
  KGS: { name: 'Kyrgyzstani Som',              symbol: 'с',    flag: '🇰🇬', country: 'Kyrgyzstan' },
  TJS: { name: 'Tajikistani Somoni',           symbol: 'SM',   flag: '🇹🇯', country: 'Tajikistan' },
  BND: { name: 'Brunei Dollar',                symbol: '$',    flag: '🇧🇳', country: 'Brunei' },
  BTN: { name: 'Bhutanese Ngultrum',           symbol: 'Nu',   flag: '🇧🇹', country: 'Bhutan' },
  MOP: { name: 'Macanese Pataca',              symbol: 'P',    flag: '🇲🇴', country: 'Macau' },

  // Europe (non-EU)
  ALL: { name: 'Albanian Lek',                 symbol: 'L',    flag: '🇦🇱', country: 'Albania' },
  BAM: { name: 'Bosnia-Herzegovina Mark',      symbol: 'KM',   flag: '🇧🇦', country: 'Bosnia & Herzegovina' },
  MKD: { name: 'Macedonian Denar',             symbol: 'ден',  flag: '🇲🇰', country: 'North Macedonia' },
  IMP: { name: 'Isle of Man Pound',            symbol: '£',    flag: '🇮🇲', country: 'Isle of Man' },

  // Americas
  BBD: { name: 'Barbadian Dollar',             symbol: '$',    flag: '🇧🇧', country: 'Barbados' },
  BMD: { name: 'Bermudian Dollar',             symbol: '$',    flag: '🇧🇲', country: 'Bermuda' },
  BOB: { name: 'Bolivian Boliviano',           symbol: 'Bs.',  flag: '🇧🇴', country: 'Bolivia' },
  BSD: { name: 'Bahamian Dollar',              symbol: '$',    flag: '🇧🇸', country: 'Bahamas' },
  BZD: { name: 'Belize Dollar',                symbol: '$',    flag: '🇧🇿', country: 'Belize' },
  CRC: { name: 'Costa Rican Colón',            symbol: '₡',    flag: '🇨🇷', country: 'Costa Rica' },
  CUP: { name: 'Cuban Peso',                   symbol: '$',    flag: '🇨🇺', country: 'Cuba' },
  DOP: { name: 'Dominican Peso',               symbol: '$',    flag: '🇩🇴', country: 'Dominican Republic' },
  GTQ: { name: 'Guatemalan Quetzal',           symbol: 'Q',    flag: '🇬🇹', country: 'Guatemala' },
  GYD: { name: 'Guyanese Dollar',              symbol: '$',    flag: '🇬🇾', country: 'Guyana' },
  HNL: { name: 'Honduran Lempira',             symbol: 'L',    flag: '🇭🇳', country: 'Honduras' },
  HTG: { name: 'Haitian Gourde',               symbol: 'G',    flag: '🇭🇹', country: 'Haiti' },
  JMD: { name: 'Jamaican Dollar',              symbol: '$',    flag: '🇯🇲', country: 'Jamaica' },
  NIO: { name: 'Nicaraguan Córdoba',           symbol: 'C$',   flag: '🇳🇮', country: 'Nicaragua' },
  PAB: { name: 'Panamanian Balboa',            symbol: 'B/.',  flag: '🇵🇦', country: 'Panama' },
  PYG: { name: 'Paraguayan Guaraní',           symbol: '₲',    flag: '🇵🇾', country: 'Paraguay' },
  SRD: { name: 'Surinamese Dollar',            symbol: '$',    flag: '🇸🇷', country: 'Suriname' },
  TTD: { name: 'Trinidad & Tobago Dollar',     symbol: '$',    flag: '🇹🇹', country: 'Trinidad & Tobago' },
  UYU: { name: 'Uruguayan Peso',               symbol: '$',    flag: '🇺🇾', country: 'Uruguay' },
  VES: { name: 'Venezuelan Bolívar',           symbol: 'Bs.S', flag: '🇻🇪', country: 'Venezuela' },
  AWG: { name: 'Aruban Florin',                symbol: 'ƒ',    flag: '🇦🇼', country: 'Aruba' },
  ANG: { name: 'Netherlands Antillean Guilder', symbol: 'ƒ',   flag: '🇨🇼', country: 'Curaçao' },
  KYD: { name: 'Cayman Islands Dollar',        symbol: '$',    flag: '🇰🇾', country: 'Cayman Islands' },

  // Oceania
  FJD: { name: 'Fijian Dollar',                symbol: '$',    flag: '🇫🇯', country: 'Fiji' },
  KID: { name: 'Kiribati Dollar',              symbol: '$',    flag: '🇰🇮', country: 'Kiribati' },
  TVD: { name: 'Tuvaluan Dollar',              symbol: '$',    flag: '🇹🇻', country: 'Tuvalu' },
  PGK: { name: 'Papua New Guinean Kina',       symbol: 'K',    flag: '🇵🇬', country: 'Papua New Guinea' },
  SBD: { name: 'Solomon Islands Dollar',       symbol: '$',    flag: '🇸🇧', country: 'Solomon Islands' },
  TOP: { name: 'Tongan Paʻanga',               symbol: 'T$',   flag: '🇹🇴', country: 'Tonga' },
  VUV: { name: 'Vanuatu Vatu',                 symbol: 'Vt',   flag: '🇻🇺', country: 'Vanuatu' },
  WST: { name: 'Samoan Tālā',                  symbol: 'WS$',  flag: '🇼🇸', country: 'Samoa' },

  // Other
  XCD: { name: 'East Caribbean Dollar',        symbol: '$',    flag: '🇦🇬', country: 'Eastern Caribbean' },
  XPF: { name: 'CFP Franc',                    symbol: 'Fr',   flag: '🇵🇫', country: 'French Polynesia' },

  // OER-only codes
  BTC: { name: 'Bitcoin',                     symbol: '₿',   flag: '🪙',  country: 'Decentralised' },
  CLF: { name: 'Chilean UF',                  symbol: 'UF',  flag: '🇨🇱', country: 'Chile' },
  CNH: { name: 'Chinese Yuan (Offshore)',      symbol: '¥',   flag: '🇨🇳', country: 'China' },
  CUC: { name: 'Cuban Convertible Peso',       symbol: '$',   flag: '🇨🇺', country: 'Cuba' },
  KPW: { name: 'North Korean Won',             symbol: '₩',   flag: '🇰🇵', country: 'North Korea' },
  SLL: { name: 'Sierra Leonean Leone (Old)',   symbol: 'Le',  flag: '🇸🇱', country: 'Sierra Leone' },
  STD: { name: 'São Tomé Dobra (Old)',         symbol: 'Db',  flag: '🇸🇹', country: 'São Tomé & Príncipe' },
  SVC: { name: 'Salvadoran Colón',             symbol: '₡',   flag: '🇸🇻', country: 'El Salvador' },
  XAG: { name: 'Silver (troy oz)',             symbol: 'XAG', flag: '🥈', country: 'Commodity' },
  XAU: { name: 'Gold (troy oz)',               symbol: 'XAU', flag: '🥇', country: 'Commodity' },
  XCG: { name: 'Caribbean Guilder',            symbol: 'ƒ',   flag: '🇨🇼', country: 'Caribbean' },
  XDR: { name: 'Special Drawing Rights',       symbol: 'SDR', flag: '🏦', country: 'IMF' },
  XPD: { name: 'Palladium (troy oz)',          symbol: 'XPD', flag: '🪨', country: 'Commodity' },
  XPT: { name: 'Platinum (troy oz)',           symbol: 'XPT', flag: '⬜', country: 'Commodity' },
  ZWG: { name: 'Zimbabwe Gold',               symbol: 'ZiG', flag: '🇿🇼', country: 'Zimbabwe' },
}

export function getCurrencyDisplay(code: string): Currency {
  const cfg = CURRENCY_CONFIG[code]
  if (cfg) return { code, ...cfg }
  return { code, name: code, symbol: code, flag: '?', country: 'Unknown' }
}

export const CURRENCY_BY_CODE: Record<string, Currency> = Object.fromEntries(
  Object.entries(CURRENCY_CONFIG).map(([code, cfg]) => [code, { code, ...cfg }])
)

export const CURRENCIES: Currency[] = Object.values(CURRENCY_BY_CODE)
