import type { Currency } from './types'

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar',            symbol: '$',    flag: '🇺🇸', country: 'United States' },
  { code: 'EUR', name: 'Euro',                  symbol: '€',    flag: '🇪🇺', country: 'European Union' },
  { code: 'GBP', name: 'British Pound',         symbol: '£',    flag: '🇬🇧', country: 'United Kingdom' },
  { code: 'JPY', name: 'Japanese Yen',          symbol: '¥',    flag: '🇯🇵', country: 'Japan' },
  { code: 'CHF', name: 'Swiss Franc',           symbol: 'Fr',   flag: '🇨🇭', country: 'Switzerland' },
  { code: 'CAD', name: 'Canadian Dollar',       symbol: '$',    flag: '🇨🇦', country: 'Canada' },
  { code: 'AUD', name: 'Australian Dollar',     symbol: '$',    flag: '🇦🇺', country: 'Australia' },
  { code: 'CNY', name: 'Chinese Yuan',          symbol: '¥',    flag: '🇨🇳', country: 'China' },
  { code: 'INR', name: 'Indian Rupee',          symbol: '₹',    flag: '🇮🇳', country: 'India' },
  { code: 'KRW', name: 'South Korean Won',      symbol: '₩',    flag: '🇰🇷', country: 'South Korea' },
  { code: 'MXN', name: 'Mexican Peso',          symbol: '$',    flag: '🇲🇽', country: 'Mexico' },
  { code: 'BRL', name: 'Brazilian Real',        symbol: 'R$',   flag: '🇧🇷', country: 'Brazil' },
  { code: 'SEK', name: 'Swedish Krona',         symbol: 'kr',   flag: '🇸🇪', country: 'Sweden' },
  { code: 'NOK', name: 'Norwegian Krone',       symbol: 'kr',   flag: '🇳🇴', country: 'Norway' },
  { code: 'DKK', name: 'Danish Krone',          symbol: 'kr',   flag: '🇩🇰', country: 'Denmark' },
  { code: 'NZD', name: 'New Zealand Dollar',    symbol: '$',    flag: '🇳🇿', country: 'New Zealand' },
  { code: 'SGD', name: 'Singapore Dollar',      symbol: '$',    flag: '🇸🇬', country: 'Singapore' },
  { code: 'HKD', name: 'Hong Kong Dollar',      symbol: '$',    flag: '🇭🇰', country: 'Hong Kong' },
  { code: 'THB', name: 'Thai Baht',             symbol: '฿',    flag: '🇹🇭', country: 'Thailand' },
  { code: 'TRY', name: 'Turkish Lira',          symbol: '₺',    flag: '🇹🇷', country: 'Turkey' },
  { code: 'ZAR', name: 'South African Rand',    symbol: 'R',    flag: '🇿🇦', country: 'South Africa' },
  { code: 'AED', name: 'UAE Dirham',            symbol: 'د.إ',  flag: '🇦🇪', country: 'United Arab Emirates' },
  { code: 'PLN', name: 'Polish Złoty',          symbol: 'zł',   flag: '🇵🇱', country: 'Poland' },
  { code: 'PHP', name: 'Philippine Peso',       symbol: '₱',    flag: '🇵🇭', country: 'Philippines' },
  // New currencies from ExchangeRate-API
  { code: 'CZK', name: 'Czech Koruna',          symbol: 'Kč',   flag: '🇨🇿', country: 'Czech Republic' },
  { code: 'HUF', name: 'Hungarian Forint',      symbol: 'Ft',   flag: '🇭🇺', country: 'Hungary' },
  { code: 'IDR', name: 'Indonesian Rupiah',     symbol: 'Rp',   flag: '🇮🇩', country: 'Indonesia' },
  { code: 'ILS', name: 'Israeli Shekel',        symbol: '₪',    flag: '🇮🇱', country: 'Israel' },
  { code: 'MYR', name: 'Malaysian Ringgit',     symbol: 'RM',   flag: '🇲🇾', country: 'Malaysia' },
  { code: 'RON', name: 'Romanian Leu',          symbol: 'lei',  flag: '🇷🇴', country: 'Romania' },
  { code: 'ISK', name: 'Icelandic Króna',       symbol: 'kr',   flag: '🇮🇸', country: 'Iceland' },
  { code: 'CLP', name: 'Chilean Peso',          symbol: '$',    flag: '🇨🇱', country: 'Chile' },
  { code: 'COP', name: 'Colombian Peso',        symbol: '$',    flag: '🇨🇴', country: 'Colombia' },
  { code: 'ARS', name: 'Argentine Peso',        symbol: '$',    flag: '🇦🇷', country: 'Argentina' },
  { code: 'PEN', name: 'Peruvian Sol',          symbol: 'S/',   flag: '🇵🇪', country: 'Peru' },
  { code: 'EGP', name: 'Egyptian Pound',        symbol: '£',    flag: '🇪🇬', country: 'Egypt' },
  { code: 'NGN', name: 'Nigerian Naira',        symbol: '₦',    flag: '🇳🇬', country: 'Nigeria' },
  { code: 'KWD', name: 'Kuwaiti Dinar',         symbol: 'KD',   flag: '🇰🇼', country: 'Kuwait' },
  { code: 'SAR', name: 'Saudi Riyal',           symbol: '﷼',    flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: 'QAR', name: 'Qatari Riyal',          symbol: '﷼',    flag: '🇶🇦', country: 'Qatar' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',     symbol: '₴',    flag: '🇺🇦', country: 'Ukraine' },
  { code: 'VND', name: 'Vietnamese Dong',       symbol: '₫',    flag: '🇻🇳', country: 'Vietnam' },
  { code: 'TWD', name: 'Taiwan Dollar',         symbol: 'NT$',  flag: '🇹🇼', country: 'Taiwan' },
  { code: 'PKR', name: 'Pakistani Rupee',       symbol: '₨',    flag: '🇵🇰', country: 'Pakistan' },
  { code: 'BDT', name: 'Bangladeshi Taka',      symbol: '৳',    flag: '🇧🇩', country: 'Bangladesh' },
  { code: 'BGN', name: 'Bulgarian Lev',         symbol: 'лв',   flag: '🇧🇬', country: 'Bulgaria' },
  { code: 'HRK', name: 'Croatian Kuna',         symbol: 'kn',   flag: '🇭🇷', country: 'Croatia' },
  { code: 'RSD', name: 'Serbian Dinar',         symbol: 'din',  flag: '🇷🇸', country: 'Serbia' },
  { code: 'GEL', name: 'Georgian Lari',         symbol: '₾',    flag: '🇬🇪', country: 'Georgia' },
  { code: 'AMD', name: 'Armenian Dram',         symbol: '֏',    flag: '🇦🇲', country: 'Armenia' },
  { code: 'KZT', name: 'Kazakhstani Tenge',     symbol: '₸',    flag: '🇰🇿', country: 'Kazakhstan' },
  { code: 'UZS', name: 'Uzbekistani Som',       symbol: "so'm", flag: '🇺🇿', country: 'Uzbekistan' },
  { code: 'AZN', name: 'Azerbaijani Manat',     symbol: '₼',    flag: '🇦🇿', country: 'Azerbaijan' },
  { code: 'BYN', name: 'Belarusian Ruble',      symbol: 'Br',   flag: '🇧🇾', country: 'Belarus' },
  { code: 'MDL', name: 'Moldovan Leu',          symbol: 'L',    flag: '🇲🇩', country: 'Moldova' },
  { code: 'MAD', name: 'Moroccan Dirham',       symbol: 'MAD',  flag: '🇲🇦', country: 'Morocco' },
  { code: 'TND', name: 'Tunisian Dinar',        symbol: 'DT',   flag: '🇹🇳', country: 'Tunisia' },
]

export const CURRENCY_BY_CODE: Record<string, Currency> = Object.fromEntries(
  CURRENCIES.map(c => [c.code, c])
)
