import type { Currency } from './types'

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar',            symbol: '$',    flag: '🇺🇸', country: 'United States' },
  { code: 'EUR', name: 'Euro',                  symbol: '€',    flag: '🇪🇺', country: 'European Union' },
  { code: 'GBP', name: 'British Pound',         symbol: '£',    flag: '🇬🇧', country: 'United Kingdom' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£',   flag: '🇫🇰', country: 'Falkland Islands' },
  { code: 'GGP', name: 'Guernsey Pound',         symbol: '£',   flag: '🇬🇬', country: 'Guernsey' },
  { code: 'GIP', name: 'Gibraltar Pound',         symbol: '£',   flag: '🇬🇮', country: 'Gibraltar' },
  { code: 'JEP', name: 'Jersey Pound',            symbol: '£',   flag: '🇯🇪', country: 'Jersey' },
  { code: 'SHP', name: 'Saint Helena Pound',      symbol: '£',   flag: '🇸🇭', country: 'Saint Helena' },
  { code: 'JPY', name: 'Japanese Yen',          symbol: '¥',    flag: '🇯🇵', country: 'Japan' },
  { code: 'CHF', name: 'Swiss Franc',           symbol: 'Fr',   flag: '🇨🇭', country: 'Switzerland' },
  { code: 'CAD', name: 'Canadian Dollar',       symbol: '$',    flag: '🇨🇦', country: 'Canada' },
  { code: 'AUD', name: 'Australian Dollar',     symbol: '$',    flag: '🇦🇺', country: 'Australia' },
  { code: 'CNY', name: 'Chinese Yuan',          symbol: '¥',    flag: '🇨🇳', country: 'China' },
  { code: 'INR', name: 'Indian Rupee',          symbol: '₹',    flag: '🇮🇳', country: 'India' },
  { code: 'KRW', name: 'South Korean Won',      symbol: '₩',    flag: '🇰🇷', country: 'South Korea' },
  { code: 'MXN', name: 'Mexican Peso',          symbol: '$',    flag: '🇲🇽', country: 'Mexico' },
  { code: 'BRL', name: 'Brazilian Real',        symbol: 'R$',   flag: '🇧🇷', country: 'Brazil' },
  { code: 'SEK', name: 'Swedish Krona',         symbol: 'kr',   flag: '🇸🇪', country: 'Sweden' },
  { code: 'NOK', name: 'Norwegian Krone',       symbol: 'kr',   flag: '🇳🇴', country: 'Norway' },
  { code: 'DKK', name: 'Danish Krone',          symbol: 'kr',   flag: '🇩🇰', country: 'Denmark' },
  { code: 'FOK', name: 'Faroese Króna',         symbol: 'kr',   flag: '🇫🇴', country: 'Faroe Islands' },
  { code: 'NZD', name: 'New Zealand Dollar',    symbol: '$',    flag: '🇳🇿', country: 'New Zealand' },
  { code: 'SGD', name: 'Singapore Dollar',      symbol: '$',    flag: '🇸🇬', country: 'Singapore' },
  { code: 'HKD', name: 'Hong Kong Dollar',      symbol: '$',    flag: '🇭🇰', country: 'Hong Kong' },
  { code: 'THB', name: 'Thai Baht',             symbol: '฿',    flag: '🇹🇭', country: 'Thailand' },
  { code: 'TRY', name: 'Turkish Lira',          symbol: '₺',    flag: '🇹🇷', country: 'Turkey' },
  { code: 'ZAR', name: 'South African Rand',    symbol: 'R',    flag: '🇿🇦', country: 'South Africa' },
  { code: 'BWP', name: 'Botswana Pula',         symbol: 'P',    flag: '🇧🇼', country: 'Botswana' },
  { code: 'AED', name: 'UAE Dirham',            symbol: 'د.إ',  flag: '🇦🇪', country: 'United Arab Emirates' },
  { code: 'PLN', name: 'Polish Złoty',          symbol: 'zł',   flag: '🇵🇱', country: 'Poland' },
  { code: 'PHP', name: 'Philippine Peso',       symbol: '₱',    flag: '🇵🇭', country: 'Philippines' },
  // New currencies from ExchangeRate-API
  { code: 'CZK', name: 'Czech Koruna',          symbol: 'Kč',   flag: '🇨🇿', country: 'Czech Republic' },
  { code: 'HUF', name: 'Hungarian Forint',      symbol: 'Ft',   flag: '🇭🇺', country: 'Hungary' },
  { code: 'IDR', name: 'Indonesian Rupiah',     symbol: 'Rp',   flag: '🇮🇩', country: 'Indonesia' },
  { code: 'ILS', name: 'Israeli Shekel',        symbol: '₪',    flag: '🇮🇱', country: 'Israel' },
  { code: 'MYR', name: 'Malaysian Ringgit',     symbol: 'RM',   flag: '🇲🇾', country: 'Malaysia' },
  { code: 'RON', name: 'Romanian Leu',          symbol: 'lei',  flag: '🇷🇴', country: 'Romania' },
  { code: 'ISK', name: 'Icelandic Króna',       symbol: 'kr',   flag: '🇮🇸', country: 'Iceland' },
  { code: 'CLP', name: 'Chilean Peso',          symbol: '$',    flag: '🇨🇱', country: 'Chile' },
  { code: 'COP', name: 'Colombian Peso',        symbol: '$',    flag: '🇨🇴', country: 'Colombia' },
  { code: 'ARS', name: 'Argentine Peso',        symbol: '$',    flag: '🇦🇷', country: 'Argentina' },
  { code: 'PEN', name: 'Peruvian Sol',          symbol: 'S/',   flag: '🇵🇪', country: 'Peru' },
  { code: 'EGP', name: 'Egyptian Pound',        symbol: '£',    flag: '🇪🇬', country: 'Egypt' },
  { code: 'NGN', name: 'Nigerian Naira',        symbol: '₦',    flag: '🇳🇬', country: 'Nigeria' },
  { code: 'KWD', name: 'Kuwaiti Dinar',         symbol: 'KD',   flag: '🇰🇼', country: 'Kuwait' },
  { code: 'SAR', name: 'Saudi Riyal',           symbol: '﷼',    flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: 'QAR', name: 'Qatari Riyal',          symbol: '﷼',    flag: '🇶🇦', country: 'Qatar' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',     symbol: '₴',    flag: '🇺🇦', country: 'Ukraine' },
  { code: 'VND', name: 'Vietnamese Dong',       symbol: '₫',    flag: '🇻🇳', country: 'Vietnam' },
  { code: 'TWD', name: 'Taiwan Dollar',         symbol: 'NT$',  flag: '🇹🇼', country: 'Taiwan' },
  { code: 'PKR', name: 'Pakistani Rupee',       symbol: '₨',    flag: '🇵🇰', country: 'Pakistan' },
  { code: 'BDT', name: 'Bangladeshi Taka',      symbol: '৳',    flag: '🇧🇩', country: 'Bangladesh' },
  { code: 'BGN', name: 'Bulgarian Lev',         symbol: 'лв',   flag: '🇧🇬', country: 'Bulgaria' },
  { code: 'HRK', name: 'Croatian Kuna',         symbol: 'kn',   flag: '🇭🇷', country: 'Croatia' },
  { code: 'RSD', name: 'Serbian Dinar',         symbol: 'din',  flag: '🇷🇸', country: 'Serbia' },
  { code: 'RUB', name: 'Russian Ruble',          symbol: '₽',    flag: '🇷🇺', country: 'Russia' },
  { code: 'GEL', name: 'Georgian Lari',         symbol: '₾',    flag: '🇬🇪', country: 'Georgia' },
  { code: 'AMD', name: 'Armenian Dram',         symbol: '֏',    flag: '🇦🇲', country: 'Armenia' },
  { code: 'KZT', name: 'Kazakhstani Tenge',     symbol: '₸',    flag: '🇰🇿', country: 'Kazakhstan' },
  { code: 'UZS', name: 'Uzbekistani Som',       symbol: "so'm", flag: '🇺🇿', country: 'Uzbekistan' },
  { code: 'AZN', name: 'Azerbaijani Manat',     symbol: '₼',    flag: '🇦🇿', country: 'Azerbaijan' },
  { code: 'BYN', name: 'Belarusian Ruble',      symbol: 'Br',   flag: '🇧🇾', country: 'Belarus' },
  { code: 'MDL', name: 'Moldovan Leu',          symbol: 'L',    flag: '🇲🇩', country: 'Moldova' },
  { code: 'MAD', name: 'Moroccan Dirham',       symbol: 'MAD',  flag: '🇲🇦', country: 'Morocco' },
  { code: 'TND', name: 'Tunisian Dinar',        symbol: 'DT',   flag: '🇹🇳', country: 'Tunisia' },

  // Africa
  { code: 'DZD', name: 'Algerian Dinar',              symbol: 'DA',   flag: '🇩🇿', country: 'Algeria' },
  { code: 'ETB', name: 'Ethiopian Birr',               symbol: 'Br',   flag: '🇪🇹', country: 'Ethiopia' },
  { code: 'GHS', name: 'Ghanaian Cedi',                symbol: '₵',    flag: '🇬🇭', country: 'Ghana' },
  { code: 'KES', name: 'Kenyan Shilling',              symbol: 'KSh',  flag: '🇰🇪', country: 'Kenya' },
  { code: 'LYD', name: 'Libyan Dinar',                 symbol: 'LD',   flag: '🇱🇾', country: 'Libya' },
  { code: 'MUR', name: 'Mauritian Rupee',              symbol: '₨',    flag: '🇲🇺', country: 'Mauritius' },
  { code: 'MZN', name: 'Mozambican Metical',           symbol: 'MT',   flag: '🇲🇿', country: 'Mozambique' },
  { code: 'RWF', name: 'Rwandan Franc',                symbol: 'RF',   flag: '🇷🇼', country: 'Rwanda' },
  { code: 'BIF', name: 'Burundian Franc',              symbol: 'Fr',   flag: '🇧🇮', country: 'Burundi' },
  { code: 'SDG', name: 'Sudanese Pound',               symbol: '£',    flag: '🇸🇩', country: 'Sudan' },
  { code: 'SSP', name: 'South Sudanese Pound',         symbol: '£',    flag: '🇸🇸', country: 'South Sudan' },
  { code: 'SOS', name: 'Somali Shilling',              symbol: 'Sh',   flag: '🇸🇴', country: 'Somalia' },
  { code: 'SZL', name: 'Swazi Lilangeni',              symbol: 'L',    flag: '🇸🇿', country: 'Eswatini' },
  { code: 'TZS', name: 'Tanzanian Shilling',           symbol: 'TSh',  flag: '🇹🇿', country: 'Tanzania' },
  { code: 'UGX', name: 'Ugandan Shilling',             symbol: 'USh',  flag: '🇺🇬', country: 'Uganda' },
  { code: 'XAF', name: 'CFA Franc BEAC',               symbol: 'Fr',   flag: '🇨🇲', country: 'Central Africa' },
  { code: 'XOF', name: 'CFA Franc BCEAO',              symbol: 'Fr',   flag: '🇸🇳', country: 'West Africa' },
  { code: 'ZMW', name: 'Zambian Kwacha',               symbol: 'ZK',   flag: '🇿🇲', country: 'Zambia' },
  { code: 'ZWL', name: 'Zimbabwean Dollar',            symbol: '$',    flag: '🇿🇼', country: 'Zimbabwe' },
  { code: 'GNF', name: 'Guinean Franc',                symbol: 'Fr',   flag: '🇬🇳', country: 'Guinea' },
  { code: 'MWK', name: 'Malawian Kwacha',              symbol: 'MK',   flag: '🇲🇼', country: 'Malawi' },
  { code: 'NAD', name: 'Namibian Dollar',              symbol: '$',    flag: '🇳🇦', country: 'Namibia' },
  { code: 'SCR', name: 'Seychellois Rupee',            symbol: '₨',    flag: '🇸🇨', country: 'Seychelles' },
  { code: 'KMF', name: 'Comorian Franc',              symbol: 'Fr',   flag: '🇰🇲', country: 'Comoros' },
  { code: 'CVE', name: 'Cape Verdean Escudo',          symbol: '$',    flag: '🇨🇻', country: 'Cape Verde' },
  { code: 'DJF', name: 'Djiboutian Franc',             symbol: 'Fr',   flag: '🇩🇯', country: 'Djibouti' },
  { code: 'ERN', name: 'Eritrean Nakfa',               symbol: 'Nfk',  flag: '🇪🇷', country: 'Eritrea' },
  { code: 'GMD', name: 'Gambian Dalasi',               symbol: 'D',    flag: '🇬🇲', country: 'Gambia' },
  { code: 'SLE', name: 'Sierra Leonean Leone',         symbol: 'Le',   flag: '🇸🇱', country: 'Sierra Leone' },
  { code: 'LRD', name: 'Liberian Dollar',              symbol: '$',    flag: '🇱🇷', country: 'Liberia' },
  { code: 'LSL', name: 'Lesotho Loti',                 symbol: 'L',    flag: '🇱🇸', country: 'Lesotho' },
  { code: 'MGA', name: 'Malagasy Ariary',              symbol: 'Ar',   flag: '🇲🇬', country: 'Madagascar' },
  { code: 'MRU', name: 'Mauritanian Ouguiya',          symbol: 'UM',   flag: '🇲🇷', country: 'Mauritania' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra',    symbol: 'Db',   flag: '🇸🇹', country: 'São Tomé & Príncipe' },
  { code: 'AOA', name: 'Angolan Kwanza',               symbol: 'Kz',   flag: '🇦🇴', country: 'Angola' },
  { code: 'CDF', name: 'Congolese Franc',              symbol: 'Fr',   flag: '🇨🇩', country: 'DR Congo' },

  // Middle East & Asia
  { code: 'AFN', name: 'Afghan Afghani',               symbol: '؋',    flag: '🇦🇫', country: 'Afghanistan' },
  { code: 'BHD', name: 'Bahraini Dinar',               symbol: 'BD',   flag: '🇧🇭', country: 'Bahrain' },
  { code: 'IQD', name: 'Iraqi Dinar',                  symbol: 'ID',   flag: '🇮🇶', country: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial',                 symbol: '﷼',    flag: '🇮🇷', country: 'Iran' },
  { code: 'JOD', name: 'Jordanian Dinar',              symbol: 'JD',   flag: '🇯🇴', country: 'Jordan' },
  { code: 'KHR', name: 'Cambodian Riel',               symbol: '៛',    flag: '🇰🇭', country: 'Cambodia' },
  { code: 'LAK', name: 'Lao Kip',                      symbol: '₭',    flag: '🇱🇦', country: 'Laos' },
  { code: 'LBP', name: 'Lebanese Pound',               symbol: 'L£',   flag: '🇱🇧', country: 'Lebanon' },
  { code: 'LKR', name: 'Sri Lankan Rupee',             symbol: '₨',    flag: '🇱🇰', country: 'Sri Lanka' },
  { code: 'MMK', name: 'Myanmar Kyat',                 symbol: 'K',    flag: '🇲🇲', country: 'Myanmar' },
  { code: 'MNT', name: 'Mongolian Tögrög',             symbol: '₮',    flag: '🇲🇳', country: 'Mongolia' },
  { code: 'MVR', name: 'Maldivian Rufiyaa',            symbol: 'Rf',   flag: '🇲🇻', country: 'Maldives' },
  { code: 'NPR', name: 'Nepalese Rupee',               symbol: '₨',    flag: '🇳🇵', country: 'Nepal' },
  { code: 'OMR', name: 'Omani Rial',                   symbol: 'ر.ع.', flag: '🇴🇲', country: 'Oman' },
  { code: 'SYP', name: 'Syrian Pound',                 symbol: '£',    flag: '🇸🇾', country: 'Syria' },
  { code: 'TMT', name: 'Turkmenistani Manat',          symbol: 'T',    flag: '🇹🇲', country: 'Turkmenistan' },
  { code: 'YER', name: 'Yemeni Rial',                  symbol: '﷼',    flag: '🇾🇪', country: 'Yemen' },
  { code: 'KGS', name: 'Kyrgyzstani Som',              symbol: 'с',    flag: '🇰🇬', country: 'Kyrgyzstan' },
  { code: 'TJS', name: 'Tajikistani Somoni',           symbol: 'SM',   flag: '🇹🇯', country: 'Tajikistan' },
  { code: 'BND', name: 'Brunei Dollar',                symbol: '$',    flag: '🇧🇳', country: 'Brunei' },
  { code: 'BTN', name: 'Bhutanese Ngultrum',           symbol: 'Nu',   flag: '🇧🇹', country: 'Bhutan' },
  { code: 'MOP', name: 'Macanese Pataca',              symbol: 'P',    flag: '🇲🇴', country: 'Macau' },

  // Europe (non-EU)
  { code: 'ALL', name: 'Albanian Lek',                 symbol: 'L',    flag: '🇦🇱', country: 'Albania' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark',      symbol: 'KM',   flag: '🇧🇦', country: 'Bosnia & Herzegovina' },
  { code: 'MKD', name: 'Macedonian Denar',             symbol: 'ден',  flag: '🇲🇰', country: 'North Macedonia' },
  { code: 'IMP', name: 'Isle of Man Pound',            symbol: '£',    flag: '🇮🇲', country: 'Isle of Man' },

  // Americas
  { code: 'BBD', name: 'Barbadian Dollar',             symbol: '$',    flag: '🇧🇧', country: 'Barbados' },
  { code: 'BMD', name: 'Bermudian Dollar',             symbol: '$',    flag: '🇧🇲', country: 'Bermuda' },
  { code: 'BOB', name: 'Bolivian Boliviano',           symbol: 'Bs.',  flag: '🇧🇴', country: 'Bolivia' },
  { code: 'BSD', name: 'Bahamian Dollar',              symbol: '$',    flag: '🇧🇸', country: 'Bahamas' },
  { code: 'BZD', name: 'Belize Dollar',                symbol: '$',    flag: '🇧🇿', country: 'Belize' },
  { code: 'CRC', name: 'Costa Rican Colón',            symbol: '₡',    flag: '🇨🇷', country: 'Costa Rica' },
  { code: 'CUP', name: 'Cuban Peso',                   symbol: '$',    flag: '🇨🇺', country: 'Cuba' },
  { code: 'DOP', name: 'Dominican Peso',               symbol: '$',    flag: '🇩🇴', country: 'Dominican Republic' },
  { code: 'GTQ', name: 'Guatemalan Quetzal',           symbol: 'Q',    flag: '🇬🇹', country: 'Guatemala' },
  { code: 'GYD', name: 'Guyanese Dollar',              symbol: '$',    flag: '🇬🇾', country: 'Guyana' },
  { code: 'HNL', name: 'Honduran Lempira',             symbol: 'L',    flag: '🇭🇳', country: 'Honduras' },
  { code: 'HTG', name: 'Haitian Gourde',               symbol: 'G',    flag: '🇭🇹', country: 'Haiti' },
  { code: 'JMD', name: 'Jamaican Dollar',              symbol: '$',    flag: '🇯🇲', country: 'Jamaica' },
  { code: 'NIO', name: 'Nicaraguan Córdoba',           symbol: 'C$',   flag: '🇳🇮', country: 'Nicaragua' },
  { code: 'PAB', name: 'Panamanian Balboa',            symbol: 'B/.',  flag: '🇵🇦', country: 'Panama' },
  { code: 'PYG', name: 'Paraguayan Guaraní',           symbol: '₲',    flag: '🇵🇾', country: 'Paraguay' },
  { code: 'SRD', name: 'Surinamese Dollar',            symbol: '$',    flag: '🇸🇷', country: 'Suriname' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar',     symbol: '$',    flag: '🇹🇹', country: 'Trinidad & Tobago' },
  { code: 'UYU', name: 'Uruguayan Peso',               symbol: '$',    flag: '🇺🇾', country: 'Uruguay' },
  { code: 'VES', name: 'Venezuelan Bolívar',           symbol: 'Bs.S', flag: '🇻🇪', country: 'Venezuela' },
  { code: 'AWG', name: 'Aruban Florin',                symbol: 'ƒ',    flag: '🇦🇼', country: 'Aruba' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ',  flag: '🇨🇼', country: 'Curaçao' },
  { code: 'KYD', name: 'Cayman Islands Dollar',        symbol: '$',    flag: '🇰🇾', country: 'Cayman Islands' },

  // Oceania
  { code: 'FJD', name: 'Fijian Dollar',                symbol: '$',    flag: '🇫🇯', country: 'Fiji' },
  { code: 'KID', name: 'Kiribati Dollar',              symbol: '$',    flag: '🇰🇮', country: 'Kiribati' },
  { code: 'TVD', name: 'Tuvaluan Dollar',              symbol: '$',    flag: '🇹🇻', country: 'Tuvalu' },
  { code: 'PGK', name: 'Papua New Guinean Kina',       symbol: 'K',    flag: '🇵🇬', country: 'Papua New Guinea' },
  { code: 'SBD', name: 'Solomon Islands Dollar',       symbol: '$',    flag: '🇸🇧', country: 'Solomon Islands' },
  { code: 'TOP', name: 'Tongan Paʻanga',               symbol: 'T$',   flag: '🇹🇴', country: 'Tonga' },
  { code: 'VUV', name: 'Vanuatu Vatu',                 symbol: 'Vt',   flag: '🇻🇺', country: 'Vanuatu' },
  { code: 'WST', name: 'Samoan Tālā',                  symbol: 'WS$',  flag: '🇼🇸', country: 'Samoa' },

  // Other
  { code: 'XCD', name: 'East Caribbean Dollar',        symbol: '$',    flag: '🇦🇬', country: 'Eastern Caribbean' },
  { code: 'XPF', name: 'CFP Franc',                    symbol: 'Fr',   flag: '🇵🇫', country: 'French Polynesia' },
]

export const CURRENCY_BY_CODE: Record<string, Currency> = Object.fromEntries(
  CURRENCIES.map(c => [c.code, c])
)
